- name: Start Windows VM
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    validate_certs: false
    node: "{{ proxmox_node }}"
    vmid: "{{ vm_id }}"
    state: started
    timeout: 180