version: '3.8'
services:
  mariadb:
    image: mariadb:11
    container_name: galera-node-76
    environment:
      - MYSQL_ROOT_PASSWORD=MeinSicheresPasswort
      - MYSQL_DATABASE=eventdb
    volumes:
      - ./conf/galera.cnf:/etc/mysql/conf.d/galera.cnf
      - db_data:/var/lib/mysql
    command:
      [
        "mariadbd",
        "--wsrep_cluster_address=gcomm://192.168.0.77,192.168.0.76,192.168.0.157",
        "--wsrep_node_name=galera-76",
        "--wsrep_node_address=192.168.0.76",
        "--port=3307"
      ]
    restart: unless-stopped
    network_mode: "host"

volumes:
  db_data:
