- name: Docker Compose Dateien auslesen
  hosts: chemnitz
  become: true
  
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    output_file: "/home/torsten/ansible/logs/all_compose_output_{{ timestamp }}.yml"


  tasks:
    - name: Inhalt der docker-compose.yml lesen
      slurp:
        src: /docker/galera/docker-compose.yml
      register: compose_file

    - name: Debug-Ausgabe auf Konsole
      debug:
        msg: "{{ compose_file['content'] | b64decode }}"

    - name: Log-Ordner auf dem Control-Node sicherstellen
      delegate_to: localhost
      become: false
      ansible.builtin.file:
        path: /home/torsten/ansible/logs
        state: directory
        mode: "0755"

    - name: Hänge Inhalt pro Host in zentrale Datei (auf Control-Node)
      delegate_to: localhost
      become: false
      ansible.builtin.blockinfile:
        path: "{{ output_file }}"
        create: yes
        marker: "### {mark} Host: {{ inventory_hostname }}"
        block: |
          {{ compose_file['content'] | b64decode | indent(2) }}
